### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Ordinary-droid** [Ordinary-droid/sudoku_solver#9]
Change the comments and make the code more readable

**Comment by Tienanh209** [comment]
Hello, Can you assign this issue for me, please ?
I would like to do it

**Comment by Ordinary-droid** [comment]
Sure yeah

**Comment by Tienanh209** [comment]
I have completed the problem, the program is above so it is easier to read and understand. Can you check it for me? Thank you

**Comment by Ordinary-droid** [comment]
Thank you!
